# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 36e6637eae7c42839237ebed88ef9940d6e30e5abfd99666a9a4591a389dd7849e1bf7036eec14aed2dbf5e8a3607a4795fc3904cf8f5539924051ccfbb373b9

test:
  secret_key_base: 132bf3d29bb1f3d88d390d58bca6173892856886241d6947bcd888d148558bec6057ba468ba615098e017cf6dd68ebd5aeda0bcf18824cfcf530bb6046a17fc9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
